spring:
  application:
    name: gateway
  profiles:
    default: default
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-auth-server
              uri: lb://MS-AUTH-SERVER
              predicates:
                - Path=/ms-auth-server/**

            - id: ms-partner
              uri: lb://MS-PARTNER
              predicates:
                - Path=/ms-partner/**

            - id: ms-meters
              uri: lb://MS-METERS
              predicates:
                - Path=/ms-meters/**

            - id: ms-readings
              uri: lb://MS-READINGS
              predicates:
                - Path=/ms-readings/**

server:
  port: 4040

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    issuer: ms-auth-server
  