spring:
  profiles:
    default: default
  application:
    name: ms-auth-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/db-users}
    username: ${SPRING_DATASOURCE_USERNAME:userAdminSigap}
    password: ${SPRING_DATASOURCE_PASSWORD:user_admin_sigap2026}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /ms-auth-server
  port: 8890

app:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    expiration-minutes: 60
    issuer: ms-auth-server

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId}] %logger{36} - %msg%n"
