spring:
  profiles:
    default: default
  application:
    name: ms-billing
  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/db-billing}
    username: ${SPRING_DATASOURCE_USERNAME:userAdminSigap}
    password: ${SPRING_DATASOURCE_PASSWORD:user_admin_sigap2026}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE:10}
      connection-timeout: ${CONNECTION_TIMEOUT:20000}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      client:
        config:
          ms-meters:
            connectTimeout: 2000
            readTimeout: 5000

server:
  port: 4045
  servlet:
    context-path: /ms-billing

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"


eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

clients:
  ms-readings:
    url: ${MS_READINGS_URL:http://localhost:4044}
