
spring:
  application:
    name: ms-partner
  profiles:
    default: default
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      minimum-idle: ${MINIMUM_IDLE}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # Crea/Actualiza las tablas automaticamente a partir de las entidades
    show-sql: true      # Permite mostrar las consultas en la consola
server:
  port: ${PORT:4041}
  address: 0.0.0.0
  servlet:
    context-path: /ms-partner

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"

eureka:
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}
    prefer-ip-address: false
    # Puerto interno real de ms-auth-server
    non-secure-port: ${PORT:4041}
    non-secure-port-enabled: true
    secure-port-enabled: false
    instance-id: ${spring.application.name}:${RAILWAY_REPLICA_ID:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
