
spring:
  application:
    name: ms-partner
  profiles:
    default: default
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:7777}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/db_socios}
    username: ${SPRING_DATASOURCE_USERNAME:userAdminSigap}
    password: ${SPRING_DATASOURCE_PASSWORD:user_admin_sigap2026}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE:5}
      connection-timeout: ${CONNECTION_TIMEOUT:20000}
  jpa:
    hibernate:
      ddl-auto: update  # Crea/Actualiza las tablas automaticamente a partir de las entidades
    show-sql: true      # Permite mostrar las consultas en la consola
server:
  port: 4041
  servlet:
    context-path: /ms-partner

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
